name: duygu_analizi
description: "Ses ve metin duygu analizi uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vocab/word_index.json
    - assets/models/en_iyi_metin_modeli.tflite